FROM rocker/r-ver:4

RUN apt-get update && apt-get install -y \
    libssl-dev \
    libcurl4-gnutls-dev \
    libxml2-dev \
    libudunits2-dev \
    libgdal-dev
RUN R -e "install.packages('devtools'); devtools::install_github('mpc-bioinformatics/ProtStatsWF')" 

ENTRYPOINT [ "/usr/local/bin/_entrypoint.sh"]

#\
# && R -e "install.packages(c('car', 'ggrepel', 'gtools', 'matrixStats', 'multcomp', 'nlme', 'openxlsx', 'pbapply', 'tidyverse'))"

#RUN R -e "if (!require('BiocManager', quietly = TRUE)) install.packages('BiocManager'); BiocManager::install(c('limma', 'affy', 'ComplexHeatmap', 'vsn'))" 